#!/bin/bash
set -euo pipefail

# Script for symlinking fonts

TARGET="$HOME/.local/share/fonts"
SOURCE="$HOME/dotfiles/misc/fonts"

while IFS= read -r font; do
  ./create_symlink "$font" "$TARGET/$(basename "$font")"
done < <(fd -t d -I . "$SOURCE")

echo "OK"
