export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
export EDITOR='nvim'
export PAGER='less'

bindkey -v

alias y='yazi'

alias td='tmux detach'
alias ta='tmux attach -t'
alias trs='tmux rename-session'

alias ga='git add'
alias gc='git commit'
alias gp='git push'

alias open='xdg-open'

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

[ -s "/Users/t/.bun/_bun" ] && source "/Users/t/.bun/_bun"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

COLIMA_SOCK="$HOME/.colima/default/docker.sock"
if [[ "$(uname -s)" != "Linux" ]] && [[ -S "$COLIMA_SOCK" ]]; then
  export DOCKER_HOST="unix://${COLIMA_SOCK}"
else
  export DOCKER_HOST="unix:///var/run/docker.sock"
fi
