#!/bin/bash
set -euo pipefail

DOTFILES="$HOME/dotfiles"
TARGET="$HOME/.local/share/fonts/"

if [ "$(uname -s)" != "Linux" ]; then 
  echo "SYSTEM IS NOT LINUX"
  exit;
fi

symlink() {
  local src="$1"
  local dest="$2"
  mkdir -p "$(dirname "$dest")"
  if [ -e "$dest" ] && [ ! -L "$dest" ]; then
    echo "file exists and is not a symlink: $dest"
    echo "(exiting)"
    exit 1
  fi
  # remove existing symlink
  if [ -L "$dest" ]; then
    rm "$dest"
    echo "removed existing symlink: $dest"
  fi
  ln -s "$src" "$dest"
  echo "linked: $src -> $dest"
}

symlink "$DOTFILES/misc/fonts/emoji" "$TARGET/emoji"
symlink "$DOTFILES/misc/fonts/sf" "$TARGET/sf"

echo "OK"
