#!/bin/bash
set -euo pipefail

### definitions ###

DOTFILES="$HOME/dotfiles"
TARGET="$HOME/.config"
IS_LINUX=$([ "$(uname -s)" = "Linux" ] && echo 1 || echo 0)

MAC_DIRS=(
  "aerospace"
  "ghostty"
  "karabiner"
)

LINUX_DIRS=(
  "i3"
  "i3blocks"
  "kitty"
  "picom"
  "rofi"
  "fontconfig"
)

SHARED_DIRS=(
  "fastfetch"
  "nvim"
  "tmux"
  "yazi"
  "git"
  "zathura"
  "mpv"
)

### symlink function ###

symlink() {
  local src="$1"
  local dest="$2"
  mkdir -p "$(dirname "$dest")"
  if [ -e "$dest" ] && [ ! -L "$dest" ]; then
    echo "file exists and is not a symlink: $dest"
    echo "(exiting)"
    exit 1
  fi
  # remove existing symlink
  if [ -L "$dest" ]; then
    rm "$dest"
    echo "removed existing symlink: $dest"
  fi
  ln -s "$src" "$dest"
  echo "linked: $src -> $dest"
}

### symlinking linux-specific configurations ### 

if [[ "$IS_LINUX" -eq 1 ]]; then
  symlink "$DOTFILES/misc/fonts/emoji" "$HOME/.local/share/fonts/emoji"
  symlink "$DOTFILES/misc/fonts/sf" "$HOME/.local/share/fonts/sf"
  symlink "$DOTFILES/misc/fonts/inter" "$HOME/.local/share/fonts/inter"
  symlink "$DOTFILES/linux/x/.xinitrc" "$HOME/.xinitrc"
  symlink "$DOTFILES/linux/x/.Xresources" "$HOME/.Xresources"
  for dir in "${LINUX_DIRS[@]}"; do
    symlink "$DOTFILES/linux/$dir" "$TARGET/$dir"
  done
fi

### symlinking mac-specific configurations ### 

if [[ "$IS_LINUX" -eq 0 ]]; then
  for dir in "${MAC_DIRS[@]}"; do
    symlink "$DOTFILES/mac/$dir" "$TARGET/$dir"
  done
fi

### symlinking shared programs ###

for dir in "${SHARED_DIRS[@]}"; do
  symlink "$DOTFILES/shared/$dir" "$TARGET/$dir"
done
symlink "$DOTFILES/shared/zsh/zshrc" "$HOME/.zshrc"
symlink "$DOTFILES/shared/starship/starship.toml" "$TARGET/starship.toml"

### symlinking scripts to .local/bin ###

for script in "$DOTFILES/scripts"/*; do
  symlink "$script" "$HOME/.local/bin/$(basename "$script")"
done

### getting firefox user profiles ###

get_firefox_profiles() {
  local base
  if [ -d "$HOME/Library/Application Support/Firefox/Profiles" ]; then
      base="$HOME/Library/Application Support/Firefox/Profiles"
  elif [ -d "$HOME/.librewolf" ]; then
      base="$HOME/.librewolf"
  else
      return
  fi
  printf '%s\n' "$base"/*.default*
}

### symlinking css for each profile ###

while IFS= read -r PROFILE; do
  [ -d "$PROFILE" ] || continue
  echo "updating firefox profile: $PROFILE"
  mkdir -p "$PROFILE/chrome"
  symlink "$DOTFILES/shared/firefox/userChrome.css" "$PROFILE/chrome/userChrome.css"
done < <(get_firefox_profiles)

### success ###
printf "\n%s\n" "OK"
