#!/bin/bash
set -euo pipefail

# Script for symlinking fonts on Linux
# Automatically symlinks from ~/dotfiles/misc/fonts/

TARGET="$HOME/.local/share/fonts"

if [ "$(uname -s)" != "Linux" ]; then 
  echo "SYSTEM IS NOT LINUX"
  exit
fi

while IFS= read -r font; do
  ./create_symlink "$font" "$TARGET/$(basename "$font")"
done < <(fd -t d -I . ~/dotfiles/misc/fonts)

echo "OK"
